version: '2'
services:
    kmk_db:
        image: mysql:5.7
        command: [
                '--default_authentication_plugin=mysql_native_password',
                '--character-set-server=utf8mb4',
                '--collation-server=utf8mb4_unicode_ci'
        ]
        environment:
            MYSQL_DATABASE: kmk_inv
            MYSQL_USER: kmk_inv
            MYSQL_PASSWORD: kmkinv
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db-kmk:/var/lib/mysql
    kmk_phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: kmk_db
            PMA_PORT: 3306
        restart: always
        ports:
            -   "8080:80"
volumes:
    db-kmk:
