index:
    path: /
    controller: App\Controller\MainController::homepage

# station

station:
    path: /stacje
    controller: App\Controller\StationController::list

station_details:
    path: /stacje/{slug}-s{id}
    controller: App\Controller\StationController::details
    requirements:
        slug: .*
        id: \d+

get_form_ajax:
    path: /stacje/ajax/pobierz-formularz-stacji
    controller: App\Controller\StationController::ajaxCreateForm
    options:
        expose: true


add_station_ajax:
    path: /stacje/ajax/dodaj-stacje
    controller: App\Controller\StationController::ajaxAddStation
    options:
        expose: true

# train

train_landing:
    path: /sklady
    controller: App\Controller\TrainController::landing

train_on_station:
    path: /sklady/stacje/{slug}-s{id}
    controller: App\Controller\TrainController::station

train_details:
    path: /sklady/{slug}-sk-{id}
    controller: App\Controller\TrainController::details
    requirements:
        slug: .*
        id: \d+

# todolist

todo_list:
    path: /do-zrobienia
    controller: App\Controller\TodoController::list

todo_list_ajax:
    path: /do-zrobienia/ajax/zmien-status
    controller: App\Controller\TodoController::changeStatus
    options:
        expose: true

todo_list_user:
    path: /do-zrobienia/{slug}-u{id}
    controller: App\Controller\TodoController::list
    requirements:
        slug: .*
        id: \d+

todo_list_add:
    path: /do-zrobienia/ajax/dodaj
    controller: App\Controller\TodoController::addTask
    options:
        expose: true

todo_list_add_admin:
    path: /do-zrobienia/ajax/administrator/dodaj
    controller: App\Controller\TodoController::addAdminTask
    options:
        expose: true

todo_list_hide:
    path: /do-zrobienia/ajax/archiwizuj
    controller: App\Controller\TodoController::hideTodo
    options:
        expose: true

# members

members_list:
    path: /czlonkowie-klubu
    controller: App\Controller\MembersController::list

# model
model_add:
    path: /modele/dodaj-model
    controller: App\Controller\ModelController::modelForm

model_add_type:
    path: /modele/dodaj-model/{type}
    controller: App\Controller\ModelController::modelForm
    requirements:
        type: .*

model_edit_type:
    path: /modele/edytuj-model/{type}/{id}
    controller: App\Controller\ModelController::modelForm
    requirements:
        type: .*
        id: \d+

model_list:
    path: /modele/lista/{type}
    controller: App\Controller\ModelController::list
    requirements:
        type: .*

# security

app_login:
    path: /zaloguj
    controller: App\Controller\SecurityController::login

app_logout:
    path: /wyloguj
    controller: App\Controller\SecurityController::logout

forget_password:
    path: /nie-pamietam-hasla
    controller: App\Controller\SecurityController::forgetPassword

reset_password:
    path: /resetuj-haslo/{hash}
    controller: App\Controller\SecurityController::forgetPassword

# administration

add_user:
    path: /administracja/dodaj-uzytkownika
    controller: App\Controller\AdminController::addUser
