index:
    path: /
    controller: App\Controller\MainController::mainAction

# station

station:
    path: /stacje
    controller: App\Controller\StationController::listAction

station_details:
    path: /stacje/{slug}-s{id}
    controller: App\Controller\StationController::detailsAction
    requirements:
        slug: .*
        id: \d+

get_form_ajax:
    path: /ajax/pobierz-formularz-stacji
    controller: App\Controller\StationController::ajaxCreateFormAction
    options:
        expose: true


add_station_ajax:
    path: /ajax/dodaj-stacje
    controller: App\Controller\StationController::ajaxAddStationAction
    options:
        expose: true

# train

train_landing:
    path: /sklady
    controller: App\Controller\TrainController::landingAction

train_on_station:
    path: /sklady/stacje/{slug}-s{id}
    controller: App\Controller\TrainController::stationAction

train_details:
    path: /sklady/{slug}-sk-{id}
    controller: App\Controller\TrainController::detailsAction
    requirements:
        slug: .*

# todolist

todo_list:
    path: /do-zrobienia
    controller: App\Controller\TodoController::listAction

todo_list_ajax:
    path: /do-zrobienia/ajax/zmien-status
    controller: App\Controller\TodoController::changeStatus
    options:
        expose: true

todo_list_user:
    path: /do-zrobienia/{slug}-u{id}
    controller: App\Controller\TodoController::listAction
    requirements:
        slug: .*
        id: \d+

todo_list_add:
    path: /do-zrobienia/ajax/dodaj
    controller: App\Controller\TodoController::addTask
    options:
        expose: true

todo_list_add_admin:
    path: /do-zrobienia/ajax/administrator/dodaj
    controller: App\Controller\TodoController::addAdminTask
    options:
        expose: true

todo_list_hide:
    path: /do-zrobienia/ajax/archiwizuj
    controller: App\Controller\TodoController::hideTodo
    options:
        expose: true

# members

members_list:
    path: /czlonkowie-klubu
    controller: App\Controller\MembersController::membersList

# security

app_login:
    path: /zaloguj
    controller: App\Controller\SecurityController::login

app_logout:
    path: /wyloguj
    controller: App\Controller\SecurityController::logout

forget_password:
    path: /nie-pamietam-hasla
    controller: App\Controller\SecurityController::forgetPassword

reser_password:
    path: /resetuj-haslo/{hash}
    controller: App\Controller\SecurityController::forgetPassword
